New branch
danilashtefan/ivt-lab pull request #3
Opened 2021-05-02 12:51 UTC by danilashtefan

2021-05-02 12:57 UTC, DinuBotan requested changes
Good job overall, but you have an unnecessary step as well.

2021-05-02 12:57 UTC, DinuBotan commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  Random generator = new Random();
Excellent work here!

2021-05-02 12:57 UTC, DinuBotan commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +
This was unnecessary..

2021-05-02 12:57 UTC, DinuBotan commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      throw new IllegalArgumentException("numberOfTorpedos");
Keep up the good work!

2021-05-02 12:57 UTC, DinuBotan commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      this.torpedoCount -= numberOfTorpedos;
Well done!

2021-05-02 13:04 UTC, DinuBotan approved these changes

2021-05-02 13:04 UTC, merged

2021-05-19 06:38 UTC, micskeiz commented
Nice work.